/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpuspgadmin;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;
import java.sql.ResultSet;
import java.util.Date;
import java.text.SimpleDateFormat;
/**
 *
 * @author CHAIRULAW
 */
public class Buku extends javax.swing.JFrame {
public Connection conn;
private java.sql.Statement cn;
public DatabaseConnection databaseConnection;
    /**
     * Creates new form Peminjaman
     */
    public Buku() {
        initComponents();
        databaseConnection = new DatabaseConnection();
        databaseConnection.koneksi();
        conn = databaseConnection.getConnection();
        cn = databaseConnection.getStatement();
        tampildata();
        bersih();
    }
    
     public class DatabaseConnection {
    private Connection conn;
    private java.sql.Statement cn;
    private final String URL = "jdbc:postgresql://localhost:5432/perpustakaan";
    private final String USER = "postgres"; // admin
    private final String PASSWORD = "admin"; // admin

    public void koneksi() {
        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(URL, USER, PASSWORD);
            cn = conn.createStatement();
            JOptionPane.showMessageDialog(null, "Koneksi berhasil.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi gagal.");
            System.out.println(e.getMessage());
        }
    }

    public Connection getConnection() {
        return conn;
    }

    public java.sql.Statement getStatement() {
        return cn;
    }
}

     public void tampildata(){
    DefaultTableModel tabelnyo = new DefaultTableModel();
    tabelnyo.addColumn("ID Buku");
    tabelnyo.addColumn("Nama Buku");
    tabelnyo.addColumn("Pengarang");
    tabelnyo.addColumn("Penerbit");
    tabelnyo.addColumn("Tanggal Terbit");
    tabelnyo.addColumn("Stok Buku");
    
    try{
    databaseConnection.koneksi();
    String sql = "SELECT * FROM bukuperpus";
    ResultSet rs= cn.executeQuery(sql);
    while(rs.next())
    {
        tabelnyo.addRow(new Object[]{
        rs.getString(1),
        rs.getString(2),
        rs.getString(3),
        rs.getString(4),
        rs.getString(5),
        rs.getString(6)
    });
    }
    
    tabelbuku.setModel(tabelnyo);
    
  }catch(Exception e){
    JOptionPane.showMessageDialog(null, "Terjadi Kesalahan menampilkan data " + e);
    System.out.println(e.getMessage());
}
    }

    void bersih(){
    idbuku.setText("");
    namabuku.setText("");
    pengarang.setText("");
    penerbit.setText("");
//    tglterbit.setDateFormatString("");
    stokbuku.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idbuku = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        namabuku = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pengarang = new javax.swing.JTextField();
        penerbit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btsimpan = new javax.swing.JButton();
        btupdate = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btexit = new javax.swing.JButton();
        stokbuku = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbuku = new javax.swing.JTable();
        tglterbit = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Buku");

        namabuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namabukuActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Buku");

        jLabel3.setText("Pengarang");

        jLabel4.setText("Penerbit");

        jLabel5.setText("TGL Terbit");

        jLabel6.setText("Stok Buku");

        btsimpan.setText("simpan");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });

        btupdate.setText("update");
        btupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdateActionPerformed(evt);
            }
        });

        bthapus.setText("hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btexit.setText("exit");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });

        tabelbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelbuku);

        tglterbit.setDateFormatString("dd MM yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(115, 115, 115)
                        .addComponent(stokbuku))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(penerbit)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tglterbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idbuku)
                            .addComponent(namabuku, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btsimpan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btupdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bthapus, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btexit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btsimpan))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namabuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btupdate))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bthapus))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btexit))
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tglterbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(stokbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namabukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namabukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namabukuActionPerformed

    private void tabelbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbukuMouseClicked
        // TODO add your handling code here:
        int row = 0;
        if(evt.getClickCount ()==1){
            row = tabelbuku.getSelectedRow();
            idbuku.setText(tabelbuku.getValueAt(row, 0).toString());
            namabuku.setText(tabelbuku.getValueAt(row, 1).toString());
            pengarang.setText(tabelbuku.getValueAt(row, 2).toString());
            penerbit.setText(tabelbuku.getValueAt(row, 3).toString());
            tglterbit.setDateFormatString(tabelbuku.getValueAt(row, 4).toString());
            stokbuku.setText(tabelbuku.getValueAt(row, 5).toString());

            idbuku.setEnabled(true);

            btsimpan.setEnabled(false);
            btupdate.setEnabled(true);
            bthapus.setEnabled(true);
        }

    }//GEN-LAST:event_tabelbukuMouseClicked

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
        try{
            databaseConnection.koneksi();
            SimpleDateFormat terbit = new SimpleDateFormat("yyyy-MM-dd");
 
            String sql ="insert into bukuperpus values ('"+ idbuku.getText() +"','"+
            namabuku.getText() +"','"+ pengarang.getText() +"','"+
            penerbit.getText() +"','"+  terbit.format(tglterbit.getDate()) +"','"+ stokbuku.getText() +"')";
            cn.executeUpdate(sql);
            tampildata();
//            conn.close();
            bersih();

            btsimpan.setEnabled(true);

            JOptionPane.showMessageDialog(null, "Data Berhasil di SIMPAN! " );

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Proses Penyimpanan Data GAGAL! " + e);
        }
    }//GEN-LAST:event_btsimpanActionPerformed

    private void btupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdateActionPerformed
        // TODO add your handling code here:
       try {
    databaseConnection.koneksi();
    SimpleDateFormat terbit = new SimpleDateFormat("yyyy-MM-dd");
    
    // Debug prints
    System.out.println("tglterbit (Date): " + tglterbit.getDate());
    System.out.println("Formatted Date: " + terbit.format(tglterbit.getDate()));
    
    String sql = "update bukuperpus set tahunterbit='"+ terbit.format(new Date()) +"', namabuku='"+ 
            namabuku.getText() +"', pengarang='"+ pengarang.getText() +"', penerbit='"+ 
            penerbit.getText() +"', stokbuku='"+ stokbuku.getText() +"' where idbuku='"+ idbuku.getText() +"'";
    cn.executeUpdate(sql);
    tampildata();
    conn.close();
    bersih();
    btsimpan.setEnabled(true);
    JOptionPane.showMessageDialog(null, "Data Berhasil Di Update");
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Update Data Gagal " + e);
}
    }//GEN-LAST:event_btupdateActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
         try{
            databaseConnection.koneksi();
            String sql="delete from bukuperpus where idbuku='"+ idbuku.getText() +"'";
            cn.executeUpdate(sql);
            tampildata();
//            conn.close();
            bersih();

            JOptionPane.showMessageDialog(null,"Data Berhasil Di Hapus");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Hapus Data Gagal" + e);
        }
    }//GEN-LAST:event_bthapusActionPerformed

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btexit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton btupdate;
    public static javax.swing.JTextField idbuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField namabuku;
    public static javax.swing.JTextField penerbit;
    public static javax.swing.JTextField pengarang;
    public static javax.swing.JTextField stokbuku;
    private javax.swing.JTable tabelbuku;
    public static com.toedter.calendar.JDateChooser tglterbit;
    // End of variables declaration//GEN-END:variables
}
