/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizlaundry;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;
import java.sql.ResultSet;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author CHAIRULAW
 */
public class layanan extends javax.swing.JFrame {
public Connection conn;
private java.sql.Statement cn;
public DatabaseConnection databaseConnection;
    /**
     * Creates new form layanan
     */
    public layanan() {
        initComponents();
        databaseConnection = new DatabaseConnection();
        databaseConnection.koneksi();
        conn = databaseConnection.getConnection();
        cn = databaseConnection.getStatement();
        tampildata();
        bersih();
    }
    
    public class DatabaseConnection {
    private Connection conn;
    private java.sql.Statement cn;
    private final String URL = "jdbc:postgresql://localhost:5432/laundry";
    private final String USER = "postgres"; // admin
    private final String PASSWORD = "admin"; // admin

    public void koneksi() {
        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(URL, USER, PASSWORD);
            cn = conn.createStatement();
            JOptionPane.showMessageDialog(null, "Koneksi berhasil.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi gagal.");
            System.out.println(e.getMessage());
        }
    }

    public Connection getConnection() {
        return conn;
    }

    public java.sql.Statement getStatement() {
        return cn;
    }
}
    
     public void tampildata(){
    DefaultTableModel tabelnyo = new DefaultTableModel();
    tabelnyo.addColumn("ID layanan");
    tabelnyo.addColumn("jenis layanan");
    tabelnyo.addColumn("lama selesai");
    
    try{
    databaseConnection.koneksi();
    String sql = "SELECT * FROM layanan";
    ResultSet rs= cn.executeQuery(sql);
    while(rs.next())
    {
        tabelnyo.addRow(new Object[]{
        rs.getString(1),
        rs.getString(2),
        rs.getString(3)
    });
    }
    
    tabellayanan.setModel(tabelnyo);
    
  }catch(Exception e){
    JOptionPane.showMessageDialog(null, "Terjadi Kesalahan menampilkan data " + e);
    System.out.println(e.getMessage());
}
    }

    void bersih(){
    idlayanan.setText("");
    jenislayanan.setText("");
    lamaselesai.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idlayanan = new javax.swing.JTextField();
        btsave = new javax.swing.JButton();
        btupdate = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btexit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jenislayanan = new javax.swing.JTextField();
        lamaselesai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabellayanan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("id layanan");

        btsave.setText("simpan");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });

        btupdate.setText("update");
        btupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdateActionPerformed(evt);
            }
        });

        bthapus.setText("hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btexit.setText("exit");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });

        jLabel2.setText("jenis layanan");

        jLabel3.setText("lama selesai");

        tabellayanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabellayanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabellayananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabellayanan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(45, 45, 45)
                                        .addComponent(idlayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(45, 45, 45)
                                        .addComponent(jenislayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btexit)
                                .addGap(37, 37, 37)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btsave, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btupdate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bthapus, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45)
                        .addComponent(lamaselesai, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btsave)
                        .addGap(102, 102, 102)
                        .addComponent(btupdate)
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bthapus)
                            .addComponent(btexit)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idlayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jenislayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lamaselesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        // TODO add your handling code here:
        try{
            databaseConnection.koneksi();
            //            SimpleDateFormat terbit = new SimpleDateFormat("yyyy-MM-dd");

            String sql ="insert into layanan values ('"+ idlayanan.getText() +"','"+
            jenislayanan.getText() +"','"+ lamaselesai.getText() +"')";
            cn.executeUpdate(sql);
            tampildata();
            //            conn.close();
            bersih();

            btsave.setEnabled(true);

            JOptionPane.showMessageDialog(null, "Data Berhasil di SIMPAN! " );

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Proses Penyimpanan Data GAGAL! " + e);
        }
    }//GEN-LAST:event_btsaveActionPerformed

    private void btupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdateActionPerformed
        // TODO add your handling code here:
        try {
            databaseConnection.koneksi();
            //            SimpleDateFormat terbit = new SimpleDateFormat("yyyy-MM-dd");
            //
            //            // Debug prints
            //            System.out.println("tglterbit (Date): " + tglterbit.getDate());
            //            System.out.println("Formatted Date: " + terbit.format(tglterbit.getDate()));

            String sql = "update layanan set jenislayanan='"+
            jenislayanan.getText() +"', lamaselesai='"+
            lamaselesai.getText() +"' where idlayanan='"+ idlayanan.getText() +"'";
            cn.executeUpdate(sql);
            tampildata();
            conn.close();
            bersih();
            btsave.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Update");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Update Data Gagal " + e);
        }
    }//GEN-LAST:event_btupdateActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        try{
            databaseConnection.koneksi();
            String sql="delete from layanan where idlayanan='"+ idlayanan.getText() +"'";
            cn.executeUpdate(sql);
            tampildata();
            //            conn.close();
            bersih();

            JOptionPane.showMessageDialog(null,"Data Berhasil Di Hapus");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Hapus Data Gagal" + e);
        }
    }//GEN-LAST:event_bthapusActionPerformed

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btexitActionPerformed

    private void tabellayananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabellayananMouseClicked
        // TODO add your handling code here:
        int row = 0;
        if(evt.getClickCount ()==1){
            row = tabellayanan.getSelectedRow();
            idlayanan.setText(tabellayanan.getValueAt(row, 0).toString());
            jenislayanan.setText(tabellayanan.getValueAt(row, 1).toString());
            lamaselesai.setText(tabellayanan.getValueAt(row, 2).toString());

            idlayanan.setEnabled(true);

            btsave.setEnabled(false);
            btupdate.setEnabled(true);
            bthapus.setEnabled(true);
        }
    }//GEN-LAST:event_tabellayananMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new layanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btexit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btsave;
    private javax.swing.JButton btupdate;
    private javax.swing.JTextField idlayanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jenislayanan;
    private javax.swing.JTextField lamaselesai;
    private javax.swing.JTable tabellayanan;
    // End of variables declaration//GEN-END:variables
}
