/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizlaundry;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;
import java.sql.ResultSet;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author CHAIRULAW
 */
public class pelanggan extends javax.swing.JFrame {
public Connection conn;
private java.sql.Statement cn;
public DatabaseConnection databaseConnection;

    /**
     * Creates new form pelanggan
     */
    public pelanggan() {
        initComponents();
        databaseConnection = new DatabaseConnection();
        databaseConnection.koneksi();
        conn = databaseConnection.getConnection();
        cn = databaseConnection.getStatement();
        tampildata();
        bersih();
    }
    
    public class DatabaseConnection {
    private Connection conn;
    private java.sql.Statement cn;
    private final String URL = "jdbc:postgresql://localhost:5432/laundry";
    private final String USER = "postgres"; // admin
    private final String PASSWORD = "admin"; // admin

    public void koneksi() {
        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection(URL, USER, PASSWORD);
            cn = conn.createStatement();
            JOptionPane.showMessageDialog(null, "Koneksi berhasil.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi gagal.");
            System.out.println(e.getMessage());
        }
    }

    public Connection getConnection() {
        return conn;
    }

    public java.sql.Statement getStatement() {
        return cn;
    }
}
    
    public void tampildata(){
    DefaultTableModel tabelnyo = new DefaultTableModel();
    tabelnyo.addColumn("ID pelanggan");
    tabelnyo.addColumn("Nama pelanggan");
    tabelnyo.addColumn("jenis kelamin");
    tabelnyo.addColumn("alamat");
    tabelnyo.addColumn("nohp");
    tabelnyo.addColumn("keterangan");
    
    try{
    databaseConnection.koneksi();
    String sql = "SELECT * FROM pelanggan";
    ResultSet rs= cn.executeQuery(sql);
    while(rs.next())
    {
        tabelnyo.addRow(new Object[]{
        rs.getString(1),
        rs.getString(2),
        rs.getString(3),
        rs.getString(4),
        rs.getString(5),
        rs.getString(6)
    });
    }
    
    tabelpelanggan.setModel(tabelnyo);
    
  }catch(Exception e){
    JOptionPane.showMessageDialog(null, "Terjadi Kesalahan menampilkan data " + e);
    System.out.println(e.getMessage());
}
    }

    void bersih(){
    idpelanggan.setText("");
    namapelanggan.setText("");
    jeniskelamin.setText("");
    alamat.setText("");
//    tglterbit.setDateFormatString("");
    nohp.setText("");
    keterangan.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btsimpan = new javax.swing.JButton();
        btupdate = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btexit = new javax.swing.JButton();
        keterangan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpelanggan = new javax.swing.JTable();
        idpelanggan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        namapelanggan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jeniskelamin = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nohp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("No HP");

        jLabel6.setText("Keterangan");

        btsimpan.setText("simpan");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });

        btupdate.setText("update");
        btupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdateActionPerformed(evt);
            }
        });

        bthapus.setText("hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btexit.setText("exit");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });

        tabelpelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelpelanggan);

        jLabel1.setText("ID Pelanggan");

        namapelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namapelangganActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama pelanggan");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Alamat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(115, 115, 115)
                        .addComponent(keterangan))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alamat)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 27, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(nohp))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idpelanggan)
                            .addComponent(namapelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btsimpan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btupdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bthapus, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btexit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btsimpan))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btupdate))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bthapus))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btexit))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
        try{
            databaseConnection.koneksi();
//            SimpleDateFormat terbit = new SimpleDateFormat("yyyy-MM-dd");

            String sql ="insert into pelanggan values ('"+ idpelanggan.getText() +"','"+
            namapelanggan.getText() +"','"+ jeniskelamin.getText() +"','"+
            alamat.getText() +"','"+ nohp.getText() +"','"+ keterangan.getText() +"')";
            cn.executeUpdate(sql);
            tampildata();
            //            conn.close();
            bersih();

            btsimpan.setEnabled(true);

            JOptionPane.showMessageDialog(null, "Data Berhasil di SIMPAN! " );

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Proses Penyimpanan Data GAGAL! " + e);
        }
    }//GEN-LAST:event_btsimpanActionPerformed

    private void btupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdateActionPerformed
        // TODO add your handling code here:
        try {
            databaseConnection.koneksi();
//            SimpleDateFormat terbit = new SimpleDateFormat("yyyy-MM-dd");
//
//            // Debug prints
//            System.out.println("tglterbit (Date): " + tglterbit.getDate());
//            System.out.println("Formatted Date: " + terbit.format(tglterbit.getDate()));

            String sql = "update pelanggan set namapelanggan='"+
            namapelanggan.getText() +"', jeniskelaminpelanggan='"+ jeniskelamin.getText() +"', alamatpelanggan='"+
            alamat.getText() +"', nohppelanggan='"+ nohp.getText() +"', keterangan='"+ keterangan.getText() +"' where idpelanggan='"+ idpelanggan.getText() +"'";
            cn.executeUpdate(sql);
            tampildata();
            conn.close();
            bersih();
            btsimpan.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Update");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Update Data Gagal " + e);
        }
    }//GEN-LAST:event_btupdateActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        try{
            databaseConnection.koneksi();
            String sql="delete from pelanggan where idpelanggan='"+ idpelanggan.getText() +"'";
            cn.executeUpdate(sql);
            tampildata();
            //            conn.close();
            bersih();

            JOptionPane.showMessageDialog(null,"Data Berhasil Di Hapus");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Hapus Data Gagal" + e);
        }
    }//GEN-LAST:event_bthapusActionPerformed

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btexitActionPerformed

    private void tabelpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpelangganMouseClicked
        // TODO add your handling code here:
        int row = 0;
        if(evt.getClickCount ()==1){
            row = tabelpelanggan.getSelectedRow();
            idpelanggan.setText(tabelpelanggan.getValueAt(row, 0).toString());
            namapelanggan.setText(tabelpelanggan.getValueAt(row, 1).toString());
            jeniskelamin.setText(tabelpelanggan.getValueAt(row, 2).toString());
            alamat.setText(tabelpelanggan.getValueAt(row, 3).toString());
            nohp.setText(tabelpelanggan.getValueAt(row, 4).toString());
            keterangan.setText(tabelpelanggan.getValueAt(row, 5).toString());

            idpelanggan.setEnabled(true);

            btsimpan.setEnabled(false);
            btupdate.setEnabled(true);
            bthapus.setEnabled(true);
        }
    }//GEN-LAST:event_tabelpelangganMouseClicked

    private void namapelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namapelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namapelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField alamat;
    private javax.swing.JButton btexit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton btupdate;
    public static javax.swing.JTextField idpelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField jeniskelamin;
    public static javax.swing.JTextField keterangan;
    public static javax.swing.JTextField namapelanggan;
    public static javax.swing.JTextField nohp;
    private javax.swing.JTable tabelpelanggan;
    // End of variables declaration//GEN-END:variables
}
